### PR TITLE
Replace --use-scoped-token with --use-scoped-token=always|never

### PR DESCRIPTION
**Pull request by grahamc**

### CODE REVIEW

**Comment by colemickens** [comment]
Do we even want to support this? Is this just for internal testing to be able to test with a coarser token?

**Comment by grahamc** [comment]
I think @cole-h wanted it for testing(?), but then yesterday we tried to use it to get out of a bind where the closure was pushed to to slice for flake A, and the flake pushed to flake B. It didn't work.

**Comment by colemickens** [comment]
do we know what didn't work? I don't see how just inverting the flag "fixes" it if something (else?) is broken.

**Comment by cole-h** [comment]
The thing that's broken here is it appears there's no way to turn this from false to true with the flag (i.e. you can't pass `--use-scoped-token false` to disable it -- we suggested trying this, and it didn't work). Inverting it means you can at least pass `--no-scoped-token` to disable the default of "yes, use a scoped token".

**Comment by grahamc** [comment]
@cole-h thanks, yeah, Cole and I chatted on a call and came around to it. He suggested using an enum and not a flag, which I agreed with, so I updated the PR.

**Review by cole-h — APPROVED** [review]

**Pull request merged**
